### ISSUE TITLE
Error in mqtt-connect.js

### ISSUE THREAD

**Issue by jizquierdo-tech** [SoftChef/cdk-iot-security#94]
Hi, I test this project and works so good, running mqtt-connect.js I received an error because in the tutorial I don't see how to generate or obtain these certificates:

const caPrivateKeyPem = readFileSync(`${__dirname}/certs/ca.private_key.pem`).toString();
const caCertificatePem = readFileSync(`${__dirname}/certs/ca.cert.pem`).toString();

**Comment by SuYehTarn** [comment]
Thank you for your report.
If you are using **JITR**, you need to download those files from the S3 bucket.
If you are using **JITP**, please refer to PR: #95, there is a modified ```mqtt-connect.js```. ```ca.private_key.pem``` and ```ca.cert.pem``` would not be needed in **JITP**.
